/**
 * The single source of truth for how the product talks to a user.
 *
 * The people this is built for are founders, product marketers, and growth
 * leads — not data engineers. They should never have to translate our internal
 * vocabulary into their own. `materiality 0.85`, `entity_match: probable`, and
 * `data class: derived` are all precise and all meaningless to the person
 * making the decision.
 *
 * Everything user-facing routes through here so a term cannot drift between
 * surfaces: the same concept must read identically on a chart, in the digest,
 * and inside the evidence drawer, or the user learns three vocabularies instead
 * of none.
 *
 * The underlying distinctions are untouched. Nothing here collapses `measured`
 * into `derived` or softens a synthetic label. The rigour stays; only the
 * wording changes.
 *
 * Rules applied throughout, from the plain-language research:
 *  - Lead with a sentence, not a label.
 *  - Never show a raw score in the primary view.
 *  - One trust cue per surface, not three competing for the same glance.
 *  - Technical detail is opt-in, never removed.
 *  - State absence in words, never as a blank.
 */

export interface PlainTerm {
  /** What the user sees. */
  label: string;
  /** One sentence, shown on demand. Answers "what does that mean?" */
  meaning: string;
  /** Tone for styling. Not a value judgment about the data itself. */
  tone: 'good' | 'caution' | 'neutral' | 'warning';
}

// ── How a number got here ───────────────────────────────────────────────────

export const DATA_CLASS: Record<'measured' | 'derived' | 'synthetic', PlainTerm> = {
  measured: {
    label: 'Read from the source',
    meaning: 'We copied this figure straight from the page or filing. No estimate involved.',
    tone: 'good',
  },
  derived: {
    label: 'Worked out by us',
    meaning:
      'We calculated this from what we collected. The inputs are real; the calculation is ours.',
    tone: 'neutral',
  },
  synthetic: {
    label: 'Simulated opinion',
    meaning:
      'Generated by a model playing a role. Not real customers, not a survey, and not a prediction.',
    tone: 'caution',
  },
};

// ── How much a change matters ───────────────────────────────────────────────

/**
 * Turn a 0–1 materiality score into something a person can act on.
 *
 * The score itself is never shown in the primary view. "0.85" requires the
 * reader to know the scale and where the threshold sits; "Worth acting on"
 * requires nothing. The number stays available in detail for anyone tuning a
 * threshold.
 */
export function importanceOf(materiality: number): PlainTerm {
  if (materiality >= 0.75) {
    return {
      label: 'Worth acting on',
      meaning:
        'A big change, from a source we trust, on something relevant to your current decision.',
      tone: 'warning',
    };
  }
  if (materiality >= 0.5) {
    return {
      label: 'Worth knowing',
      meaning: 'A real change, but not one that demands a response this week.',
      tone: 'caution',
    };
  }
  return {
    label: 'Minor',
    meaning:
      'Small, or from a source we trust less. Kept for the record but not worth interrupting you.',
    tone: 'neutral',
  };
}

// ── Whether it is really about the right company ────────────────────────────

export const ENTITY_MATCH: Record<
  'confirmed' | 'probable' | 'unverified' | 'mismatch',
  PlainTerm
> = {
  confirmed: {
    label: 'Definitely them',
    meaning: 'The page names the company directly, so there is no ambiguity.',
    tone: 'good',
  },
  probable: {
    label: 'Probably them',
    meaning: 'Strong signals point to this company, but the page does not name it outright.',
    tone: 'caution',
  },
  unverified: {
    label: 'Not confirmed',
    meaning:
      'We could not confirm this is about the right company. Treat anything resting on it carefully.',
    tone: 'caution',
  },
  mismatch: {
    label: 'Different company',
    meaning:
      'This turned out to be about someone else. It no longer supports any finding, but we kept it so you can see what we looked at.',
    tone: 'warning',
  },
};

// ── Whether someone said it, or we concluded it ─────────────────────────────

export const CLAIM_TYPE: Record<'fact' | 'interpretation' | 'assumption', PlainTerm> = {
  fact: {
    label: 'Backed by a quote',
    meaning: 'Someone stated this in a source we read, and we kept their exact words.',
    tone: 'good',
  },
  interpretation: {
    label: 'Our read',
    meaning:
      'Our analysis of what the evidence adds up to. Reasonable, but nobody stated it outright.',
    tone: 'neutral',
  },
  assumption: {
    label: 'Assumed',
    meaning: 'Taken as a starting point for this scenario. Not established.',
    tone: 'caution',
  },
};

// ── How fresh something is ──────────────────────────────────────────────────

/**
 * Freshness in words rather than a timestamp.
 *
 * "Checked today" and "Last checked 47 days ago — may be out of date" both tell
 * a user what to do. A raw ISO date makes them do the arithmetic.
 */
export function freshnessOf(iso: string | null | undefined): PlainTerm {
  if (!iso) {
    return {
      label: 'Never checked',
      meaning:
        'We have not looked at this source yet, so we cannot say whether anything changed there.',
      tone: 'warning',
    };
  }

  const days = Math.floor((Date.now() - new Date(iso).getTime()) / 86_400_000);

  if (Number.isNaN(days)) {
    return { label: 'Unknown', meaning: 'We could not read the date on this.', tone: 'neutral' };
  }
  if (days <= 0) return { label: 'Checked today', meaning: 'As current as it gets.', tone: 'good' };
  if (days === 1) return { label: 'Checked yesterday', meaning: 'Still current.', tone: 'good' };
  if (days <= 7) {
    return { label: `Checked ${days} days ago`, meaning: 'Recent enough to rely on.', tone: 'good' };
  }
  if (days <= 30) {
    return {
      label: `Checked ${days} days ago`,
      meaning: 'Still reasonably current, but worth refreshing before a big decision.',
      tone: 'neutral',
    };
  }
  return {
    label: `Last checked ${days} days ago`,
    meaning: 'Old enough that it may be out of date. Refresh before relying on it.',
    tone: 'caution',
  };
}

// ── What kind of change happened ────────────────────────────────────────────

/**
 * Event types as a person would describe them.
 *
 * `pricing_changed` is a database value. "changed their pricing" is a sentence
 * fragment that reads naturally after a company name.
 */
export const EVENT_DESCRIPTION: Record<string, string> = {
  pricing_changed: 'changed their pricing',
  feature_launched: 'shipped something new',
  feature_removed: 'removed a feature',
  positioning_changed: 'changed how they describe themselves',
  segment_changed: 'shifted who they are selling to',
  integration_announced: 'announced an integration',
  hiring_signal: 'showed a hiring signal',
  funding_or_filing: 'filed or raised money',
  review_theme: 'shifted in what customers say',
  documentation_changed: 'updated their documentation',
};

export function describeEvent(eventType: string): string {
  return EVENT_DESCRIPTION[eventType] ?? eventType.replace(/_/g, ' ');
}

// ── Tone → styling ──────────────────────────────────────────────────────────

/**
 * One place where tone becomes colour, so a "caution" reads the same on every
 * surface. A user who learns the colour once should not have to relearn it.
 */
export const TONE_CLASS: Record<PlainTerm['tone'], string> = {
  good: 'bg-emerald-50 text-emerald-600 border-emerald-200',
  caution: 'bg-amber-50 text-amber-700 border-amber-200',
  warning: 'bg-red-50 text-red-600 border-red-200',
  neutral: 'bg-muted text-muted-foreground border-border',
};

// ── Glossary ────────────────────────────────────────────────────────────────

export interface GlossaryEntry {
  term: string;
  plain: string;
}

/**
 * Every term the product uses, defined.
 *
 * Only about one in six analytics platforms ships a glossary, despite a
 * measurable effect on user confidence. It costs almost nothing and answers the
 * question a user would otherwise have to guess at or ask support.
 */
export const GLOSSARY: GlossaryEntry[] = [
  {
    term: 'Read from the source',
    plain:
      'We copied the figure straight from the page. If you open the quote, you will see the same number.',
  },
  {
    term: 'Worked out by us',
    plain:
      'We calculated it from things we collected. The inputs are real; the arithmetic is ours, and we show it.',
  },
  {
    term: 'Simulated opinion',
    plain:
      'A model played the role of a buyer and gave an opinion. Useful for finding objections you had not thought of. Not real customers, and not a forecast.',
  },
  {
    term: 'Quote',
    plain:
      'The exact words we found on a page, saved so you can check them yourself. Every finding that says "backed by a quote" has one.',
  },
  {
    term: 'Worth acting on',
    plain:
      'A big change, from a source we trust, on something relevant to the decision you told us about.',
  },
  {
    term: 'Page version',
    plain:
      'A fingerprint of the page as we saved it. It lets you confirm a quote came from that exact version, even if the page has changed since.',
  },
  {
    term: 'Never checked',
    plain:
      'We have not looked at that source. It does not mean nothing happened there — it means we cannot say.',
  },
  {
    term: 'Nothing changed',
    plain:
      'We looked and the page was identical to last time. That is a real answer, and it costs us almost nothing to confirm.',
  },
  {
    term: 'Our read',
    plain:
      'Our analysis rather than something a source stated. Reasonable, but nobody actually said it, so we label it differently.',
  },
];
